revisor:
    notify_on_failures: 100
client:
    uri: http://youtube.com/
validator:
    codes:
        - 200
        - 301
        - 302
        - 304
    min_time: 0.11
notifier:
    notify_with: 
        - email
        - sms
    transport:
        email: 
            from: alert@revisor.com
            subject: youtube.com site watching
            to: vbuzrvcd@sharklasers.com
        sms: 
            api_key: asdfasdfasdfasdf
            api_secret: qwerqwerqwerqwerqwerqwer
            phone_number: +375291111111
            from: revisor_app