revisor:
    notify_on_failures: 5
client:
    uri: http://youtube.com/
validator:
    codes:
        - 200
        - 301
        - 302
        - 304
    min_time: 0.11
notifier:
    notify_with: 
        - email
        - sms
    transport:
        email: 
            to: 
        sms: 
            api_key: asdfasdfasdfasdf
            api_secret: qwerqwerqwerqwerqwerqwer
            phone_number: +375291111111
            from: revisor_app