revisor:
    reply_on_x: 5
client:
    uri: http://youtube.com/
validator:
    codes:
        - 200
        - 301
        - 302
        - 304
    min_time: 0.3
notifier:
    notify_with: ['email']
    transport:
        email: ~
        sms: ~